name: 'Release Gem to GitHub Packages'
description: 'Builds and publishes Ruby gems to GitHub Packages'
author: 'Jan Stastny'
branding:
  color: green
  icon: upload-cloud
inputs:
  token:
    description: 'GitHub token that has access to write to GitHub package registry. You can use GITHUB_TOKEN for this.'
    required: true
  user:
    description: 'GitHub user that has access to commit to repository.'
    required: true
  email:
    description: 'GitHub email that has access to commit to repository.'
    required: true
  owner:
    description: 'Name of the user or organization account that owns the repository containing your project.'
    required: false
  working-directory:
    description: 'An optional path to switch to before building the Gem.'
    required: false
  branch:
    description: 'An optional branch to push version bump.'
    required: false
  skip_tag:
    description: 'Skip Bumping and pushing tags step.'
    required: false
  default_branch:
    description: 'the default branch to push gem tags ex. master|main'
    required: false
    default: master

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.user }}
    - ${{ inputs.email }}
    - ${{ inputs.owner }}
    - ${{ inputs.working-directory }}
    - ${{ inputs.branch }}
    - ${{ inputs.skip_tag }}
    - ${{ inputs.default_branch }}
